2024-02-18 23:56:28,726 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-18 23:56:28,726 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Configure stats pid to 31256
2024-02-18 23:56:28,728 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-18 23:56:28,728 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-18 23:56:28,728 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-18 23:56:28,728 INFO    MainThread:31256 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-18 23:56:28,729 INFO    MainThread:31256 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_235628-kxl58bgo\logs\debug.log
2024-02-18 23:56:28,729 INFO    MainThread:31256 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_235628-kxl58bgo\logs\debug-internal.log
2024-02-18 23:56:28,730 INFO    MainThread:31256 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000286C8BD6C80>
2024-02-18 23:56:28,730 INFO    MainThread:31256 [wandb_init.py:init():566] calling init triggers
2024-02-18 23:56:28,730 INFO    MainThread:31256 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 2, 'max_depth': 41}
2024-02-18 23:56:28,730 INFO    MainThread:31256 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 4jyb4ehp
2024-02-18 23:56:28,732 INFO    MainThread:31256 [wandb_run.py:_finish():1970] finishing run mc0c0z/DecisionTree/4jyb4ehp
2024-02-18 23:56:28,732 INFO    MainThread:31256 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-18 23:56:28,732 INFO    MainThread:31256 [wandb_run.py:_restore():2193] restore
2024-02-18 23:56:28,732 INFO    MainThread:31256 [wandb_run.py:_restore():2199] restore done
2024-02-18 23:56:29,839 INFO    MainThread:31256 [wandb_init.py:init():616] starting backend
2024-02-18 23:56:29,840 INFO    MainThread:31256 [wandb_init.py:init():620] setting up manager
2024-02-18 23:56:29,841 INFO    MainThread:31256 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-18 23:56:29,842 INFO    MainThread:31256 [wandb_init.py:init():628] backend started and connected
2024-02-18 23:56:29,850 INFO    MainThread:31256 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-18 23:56:29,850 INFO    MainThread:31256 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-18 23:56:29,850 INFO    MainThread:31256 [wandb_init.py:init():720] updated telemetry
2024-02-18 23:56:29,852 INFO    MainThread:31256 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
