2024-02-19 20:34:59,755 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 20:34:59,755 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Configure stats pid to 19448
2024-02-19 20:34:59,755 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-19 20:34:59,756 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-19 20:34:59,756 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-19 20:34:59,756 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 20:34:59,757 INFO    MainThread:19448 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_203459-qlj87dl7\logs\debug.log
2024-02-19 20:34:59,757 INFO    MainThread:19448 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_203459-qlj87dl7\logs\debug-internal.log
2024-02-19 20:34:59,757 INFO    MainThread:19448 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000025BD76751E0>
2024-02-19 20:34:59,757 INFO    MainThread:19448 [wandb_init.py:init():566] calling init triggers
2024-02-19 20:34:59,757 INFO    MainThread:19448 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 2, 'max_depth': 1}
2024-02-19 20:34:59,758 INFO    MainThread:19448 [wandb_init.py:init():616] starting backend
2024-02-19 20:34:59,758 INFO    MainThread:19448 [wandb_init.py:init():620] setting up manager
2024-02-19 20:34:59,759 INFO    MainThread:19448 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-19 20:34:59,761 INFO    MainThread:19448 [wandb_init.py:init():628] backend started and connected
2024-02-19 20:34:59,768 INFO    MainThread:19448 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 20:34:59,771 INFO    MainThread:19448 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 20:34:59,771 INFO    MainThread:19448 [wandb_init.py:init():720] updated telemetry
2024-02-19 20:34:59,772 INFO    MainThread:19448 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 20:35:02,805 WARNING MainThread:19448 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "f:\test\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "f:\test\lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "f:\test\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "f:\test\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "f:\test\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "f:\test\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "f:\test\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-02-19 20:35:25,026 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 20:35:25,026 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Configure stats pid to 19448
2024-02-19 20:35:25,026 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-19 20:35:25,026 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-19 20:35:25,027 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-19 20:35:25,027 INFO    MainThread:19448 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 20:35:25,027 INFO    MainThread:19448 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_203525-cuvzg9mo\logs\debug.log
2024-02-19 20:35:25,027 INFO    MainThread:19448 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_203525-cuvzg9mo\logs\debug-internal.log
2024-02-19 20:35:25,029 INFO    MainThread:19448 [wandb_init.py:init():566] calling init triggers
2024-02-19 20:35:25,029 INFO    MainThread:19448 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 2, 'max_depth': 1}
2024-02-19 20:35:25,029 INFO    MainThread:19448 [wandb_init.py:init():616] starting backend
2024-02-19 20:35:25,029 INFO    MainThread:19448 [wandb_init.py:init():620] setting up manager
2024-02-19 20:35:25,031 INFO    MainThread:19448 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-19 20:35:25,031 INFO    MainThread:19448 [wandb_init.py:init():628] backend started and connected
2024-02-19 20:35:25,039 INFO    MainThread:19448 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 20:35:25,039 INFO    MainThread:19448 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 20:35:25,040 INFO    MainThread:19448 [wandb_init.py:init():720] updated telemetry
2024-02-19 20:35:25,041 INFO    MainThread:19448 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 20:36:55,958 ERROR   MainThread:19448 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-19 20:36:56,281 ERROR   MainThread:19448 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "f:\test\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "f:\test\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
